### PR TITLE
Improve PerfCounterPlugin

### PR DESCRIPTION
**Pull request by seidler2547**
PerfCounterPlugin now accepts regular expressions to include/exclude counters
many issues with localized version of Windows have been resolved
encoding issues and issues with label text have been resolved

### CODE REVIEW

**Comment by seidler2547** [comment]
Hi, I realize this is a big pull request, but I wanted to make sure that things will work alright. I have tested this mostly on German Windows 2012R2 servers, but also on some Windows 7 and 8/8.1 machines.

I plan to write some documentation and sample plugin configs soon.

I feel that this plugin is now at such a universally usable state that it would almost make sense to have a "plugin config" repository. It basically provides a lot of the flexibility that the Linux munin-node provides in that additional Performance Counter plugins can be written just using some regular expressions and maybe a formula.

Missing (and probably trivial to add) would be the definition of warning and critical values for the plugin sections.

**Comment by seidler2547** [comment]
Sorry, something seemed to have gone wrong with rebasing. I will try to resubmit shortly.

**Comment by seidler2547** [comment]
Reopening after having found the issue.

**Comment by seidler2547** [comment]
Here's a first attempt at documentation: https://github.com/seidler2547/munin-node-win32/wiki

**Comment by rrzefox** [comment]
I'm not sure about the license of the deelx.h you include. Its webpage states that it's "free for commercial and noncommercial use", but that is not mentioned in the file itself, and I doubt this is really compatible with GPLv3. (And BTW: munin-node-win32 is declared as GPLv3 on code.google.com and in some individual sourcecode files, but I see no LICENSE file in the source repository. This should probably be added)

**Comment by seidler2547** [comment]
Yeah I was afraid that would become an issue. Would there be a license that would be compatible with GPL and would allow them to keep the "noncommercial" restriction? Or are there any GPL regex libraries I could use instead?

**Comment by kenyon** [comment]
I don't see any noncommercial restriction. The web page says "DEELX is free for personal use and commercial use." That sounds pretty permissive to me.

**Comment by rrzefox** [comment]
Unfortunately, "free to use" does not imply "free to modify" and all those things that GPL grants you. In fact it doesn't even imply "free to redistribute the source code".

**Pull request merged**
