### PR TITLE
Minor cleanup and updated installer

### PR DESCRIPTION
**Pull request by TcT2k**
- Included log spam fix from @joshrobb [See here](https://github.com/joshrobb/munin-node-win32/commit/f4605659115b39d2f471f4483b051202ff635ac5)
- Included x64 version of installer
- Build win32 release version with static runtime
- Updated installer to use "Modern UI 2"

Binaries available [here](https://github.com/TcT2k/munin-node-win32/releases)

### CODE REVIEW

**Comment by Elbandi** [comment]
the "log spam fix" commit breaks the codestyle (tab vs space indent)

**Comment by TcT2k** [comment]
@Elbandi updated commit to use spaces

**Comment by tgutzler** [comment]
Is anyone still working on this?
I downloaded the 64bit installer from https://github.com/TcT2k/munin-node-win32/releases. File properties claim version 1.6.1 but it reports as version 1.6.0 and the cpu stats are 0.00000

**Comment by tgutzler** [comment]
Got it to work by applying the changes from this PR: https://github.com/munin-monitoring/munin-node-win32/pull/66/files

**Comment by lemontree23** [comment]
Fixes already in newest version. :)

**Pull request closed without merging**
